- hosts: webservers
  become: yes
  become_user: root
  vars:
    nginx_user: nginx
    nginx_root: /usr/share/nginx/html
    nginx_index: index.html
    nginx_config_file: /etc/nginx/nginx.conf
    nginx_port: 80
    log_config:
      access_path: "/var/log/nginx/access.log"
      error_path: "/var/log/nginx/error.log"
  tasks:
    - name: Install nginx
      ansible.builtin.include_role:
        name: nginxinc.nginx

    - name: Copy Nginx configuration file
      template:
        src: nginx.conf.j2
        dest: "{{ nginx_config_file }}"
        mode: '0644'

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes
